"""
End-to-end pipeline test for Nx2PTCorrelationFunction using emulator weights.
Tests that the full JIT-compiled pipeline runs correctly with all four
config-space observables: w(theta), gamma_t, xi+, xi-.

This is the production-mode test — unlike test_pipeline_end_to_end.py which
uses CLASS (not JIT-compatible), this test uses the neural network emulators
and runs with full JAX JIT compilation, enabling NUTS sampling.

Requirements:
- Emulator weights in gholax/theory/emu_weights/
- Dummy data vector generated by examples/generate_dummy_datavector.py

Run from repo root with:
    python examples/test_configspace_pipeline_end_to_end_emulator.py
"""
import os
import sys
import jax
import jax.numpy as jnp
import yaml

os.environ["JAX_PLATFORMS"] = "cpu"

config_path = "examples/config_configspace_emulator.yaml"
if not os.path.exists(config_path):
    print(f"Config file not found: {config_path}")
    print("Run from the repo root directory.")
    sys.exit(1)

with open(config_path) as f:
    cfg = yaml.safe_load(f)

print("Building model (loading emulators)...")
from gholax.util.model import Model
model = Model(cfg)
like = model.likelihoods["Nx2PTCorrelationFunction"]
print("Model built successfully.")
print(f"Free parameters: {model.param_names}")
print(f"Reference values: {dict(zip(model.param_names, model.prior.reference_values))}")

# ---- Test 1: JIT-compiled likelihood evaluation ----
print("\n=== Test 1: JIT-compiled likelihood evaluation ===")
param_vec = jnp.zeros(len(model.prior.reference_values))
print("Compiling with JIT (first call may be slow)...")
from jax.tree_util import Partial
log_posterior_jit = jax.jit(Partial(model.log_posterior_scaled_params))
lp = log_posterior_jit(param_vec)
print(f"log_posterior at reference cosmology: {lp:.6e}")

if jnp.isfinite(lp):
    print("SUCCESS: JIT-compiled pipeline produced a finite likelihood.")
else:
    print("FAIL: log_posterior is not finite.")
    sys.exit(1)

# ---- Test 2: gradient computation ----
print("\n=== Test 2: Gradient computation ===")
print("Computing gradient of log_posterior w.r.t. parameters...")
grad_fn = jax.jit(jax.grad(model.log_posterior_scaled_params))
grad = grad_fn(param_vec)
print(f"Gradient shape: {grad.shape}")
print(f"Gradient finite: {jnp.all(jnp.isfinite(grad))}")
print(f"Gradient: {dict(zip(model.param_names, grad))}")

if jnp.all(jnp.isfinite(grad)):
    print("SUCCESS: Gradients are finite — NUTS sampling is possible.")
else:
    print("FAIL: Non-finite gradients detected.")
    sys.exit(1)

# ---- Test 3: model vector check ----
print("\n=== Test 3: Model vector ===")
params_all = dict(zip(model.param_names, model.prior.reference_values))
model_vec, state = like.predict_model(params_all, {}, return_state=True)
print(f"Model vector shape: {model_vec.shape}")
print(f"Model vector finite: {jnp.all(jnp.isfinite(model_vec))}")

# Check each observable
for key, label in [
    ("w_0_0_obs",       "w(theta) bin(0,0)"),
    ("gamma_0_0_obs",   "gamma_t  bin(0,0)"),
    ("xi_pos_0_0_obs",  "xi+      bin(0,0)"),
    ("xi_neg_0_0_obs",  "xi-      bin(0,0)"),
]:
    if key in state:
        arr = state[key]
        print(f"  {label}: min={jnp.min(arr):.4e}, max={jnp.max(arr):.4e}, "
              f"finite={jnp.all(jnp.isfinite(arr))}")
    else:
        print(f"  {label}: MISSING from state")

# ---- Test 4: chi-squared check ----
print("\n=== Test 4: Chi-squared at reference cosmology ===")
data = like.observed_data_vector.spectrum_values[like.observed_data_vector.scale_mask]
diff = model_vec - data
cinv = like.observed_data_vector.cinv
chi2 = diff @ cinv @ diff
rel_diff = jnp.max(jnp.abs(diff / data))
print(f"Max relative difference (theory vs data): {rel_diff:.4e}")
print(f"Chi-squared: {chi2:.4e}")
if chi2 < 1.0:
    print("Chi-squared check PASSED.")
else:
    print("Chi-squared check FAILED — data may not match reference cosmology.")
    print("Re-run generate_dummy_datavector.py to regenerate data at reference cosmology.")

print("\n=== All tests passed ===")
print("\nThe pipeline is JIT-compiled and gradients are finite.")
print("Ready for NUTS sampling:")
print("  run-gholax examples/config_configspace_emulator.yaml")
